# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "49e6ec7fb69ed11a4e11f2d7231d6ea5"
name = "comeback"
handle = "comeback-3"
application_url = "https://projector-magnitude-manufactured-automation.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "customers/create" ]
  uri = "/api/webhooks/customers/create"

  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/api/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/api/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/api/webhooks/orders/paid"

  [[webhooks.subscriptions]]
  topics = [ "refunds/create" ]
  uri = "/api/webhooks/refunds/create"

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/api/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_orders"

[auth]
redirect_urls = [
  "https://projector-magnitude-manufactured-automation.trycloudflare.com/auth/callback",
  "https://projector-magnitude-manufactured-automation.trycloudflare.com/auth/shopify/callback",
  "https://projector-magnitude-manufactured-automation.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
