# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "49e6ec7fb69ed11a4e11f2d7231d6ea5"
name = "comeback"
handle = "comeback-3"
application_url = "https://myth-signs-kg-trend.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,write_orders,read_customers"

[auth]
redirect_urls = [
  "https://myth-signs-kg-trend.trycloudflare.com/auth/callback",
  "https://myth-signs-kg-trend.trycloudflare.com/auth/shopify/callback",
  "https://myth-signs-kg-trend.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
