"""Add reason column to loyalty_points table

Revision ID: c3154ddad1d7
Revises: d89865a9addc
Create Date: 2025-05-25 15:21:10.759559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3154ddad1d7'
down_revision: Union[str, None] = 'd89865a9addc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loyalty_points', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loyalty_points', 'reason')
    # ### end Alembic commands ###
